

CREATE View [dbo].[QB_InvoiceExport_TransactionPro] 
as
--select 'Customer',
--'Transaction Date',
--'RefNumber',
--'PO Number',
--'Terms',
--'Class',
--'Template Name',
--'To Be Printed',
--'Ship Date',
--'BillTo Line1',
--'BillTo Line2',
--'BillTo Line3',
--'BillTo Line4',
--'BillTo City',
--'BillTo State',
--'BillTo PostalCode',
--'BillTo Country',
--'ShipTo Line1',
--'ShipTo Line2',
--'ShipTo Line3',
--'ShipTo Line4',
--'ShipTo City',
--'ShipTo State',
--'ShipTo PostalCode',
--'ShipTo Country',
--'Phone',
--'Fax',
--'Email',
--'Contact Name',
--'First Name',
--'Last Name',
--'Rep',
--'Due Date',
--'Ship Method',
--'Customer Message',
--'Memo',
--'Cust. Tax Code',
--'Item',
--'Quantity',
--'Description',
--'Price',
--'Is Pending',
--'Item Line Class',
--'Service Date',
--'FOB',
--'Customer Acct No',
--'Sales Tax Item',
--'To Be E-Mailed',
--'Other',
--'Other1',
--'Other2',
--'Unit of Measure',
--'AR Account',
--'Currency',
--'Exchange Rate',
--'Sales Tax Code'
--union all
select c.CustID as Customer, convert(Varchar(10), A.InvoiceDate,101) as [Transaction Date],	
B.Container as RefNumber, E.OrderNo [PO Number], '' Terms,	'' Class,	'' [Template Name],	
'N' as [To Be Printed],	'' as [Ship Date], F.AddrName as [BillTo Line1], F.Address1 as [BillTo Line],	
F.Address2 as [BillTo Line3], '' [BillTo Line4],	
F.City as  [BillTo City], F.State as [BillTo State], F.ZipCode as [BillTo PostalCode],	
F.Country as [BillTo Country], F.AddrName as [ShipTo Line1],  F.Address1 as	[ShipTo Line2],
F.Address2  as [ShipTo Line3],'' [ShipTo Line4],	
F.City  [ShipTo City],  F.State [ShipTo State'], F.ZipCode as	[ShipTo PostalCode], F.Country  as [ShipTo Country],	
F.Phone as Phone, F.Fax as Fax, F.Email as Email, '' as  [Contact Name],
'' as [First Name],	'' as [Last Name], '' as  Rep, convert(Varchar(10), DueDate,101)	as [Due Date],'' as [Ship Method],	
'' as [Customer Message], '' as Memo, '' as [Cust. Tax Code],	
G.ItemId as Item, CONVERT(Varchar, b.Qty) as Quantity,
B.Description as [Description], convert(varchar, B.UnitPrice) as Price, '' as [Is Pending],
'' as [Item Line Class], '' as [Service Date],
'' as [FOB],
'' as [Customer Acct No],
'' as [Sales Tax Item],
'' as [To Be E-Mailed],	
'' as [Other],	
'' as [Other1],	
'' as [Other2], '' as [Unit of Measure], '' as [AR Account],	
'' as [Currency],	'' as [Exchange Rate],	'' as [Sales Tax Code]
 from InvoiceHeader A WITH (NOLOCK) 
inner join Invoicedetail B WITH (NOLOCK)  on (A.InvoiceKey = B.InvoiceKey)
inner join Customer  C WITH (NOLOCK)  on (A.CustKey = C.CustKey)
inner join OrderDetail D WITH (NOLOCK)  on (B.OrderDetailKey = D.OrderDetailKey) 
inner join OrderHeader E WITH (NOLOCK)  on (D.OrderKey = E.OrderKey)
inner join Address F WITH (NOLOCK)  on (A.BillToAddrKey = F.AddrKey)
inner join Item G WITH (NOLOCK)  on (B.ItemKey = G.ItemKey)

 
