CREATE VIEW [dbo].[v_DateRanges]
AS
SELECT 'Past' AS RangeName,
       CAST(DATEADD(DAY, -2, CAST(GETDATE() AS DATE)) AS DATE) AS StartDate,
       CAST(DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AS DATE) AS EndDate

UNION ALL
SELECT 'Yesterday',
       CAST(DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AS DATE),
       CAST(DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AS DATE)

UNION ALL
SELECT 'Today',
       CAST(GETDATE() AS DATE),
       CAST(GETDATE() AS DATE)

UNION ALL
SELECT 'Tomorrow',
       CAST(DATEADD(DAY, 1, CAST(GETDATE() AS DATE)) AS DATE),
       CAST(DATEADD(DAY, 1, CAST(GETDATE() AS DATE)) AS DATE)

UNION ALL
SELECT 'This Week',
       DATEADD(DAY, 1 - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE)), 
       DATEADD(DAY, 7 - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE))

UNION ALL
SELECT 'Future',
       DATEADD(DAY, 2, CAST(GETDATE() AS DATE)),
       NULL AS EndDate;
