



CREATE PROCEDURE [dbo].[DB_CompareTables_Table]

AS

DECLARE @FromDB VARCHAR(50), @ToDB VARCHAR(50)

SET @FromDB = (SELECT Top 1 DBNAME FROM DB_CompareData )
SET @ToDB = (SELECT DB_name() )

SELECT		*
INTO		#TESTDATAPROC
FROM		DB_CompareData 
WHERE		ISPROC = 0  AND TABLE_NAME NOT IN ('UserInfo-old')  AND TABLE_NAME  NOT LIKE '%_Prev%' -- Tables not required from UAT

-- SELECT * FROM DB_CompareData WHERE TABLE_NAME = 'Roshan'

IF OBJECT_ID('tempdb..#TMP1') is not null

BEGIN
	DROP TABLE #TMP1
END;

 WITH q AS (    
		SELECT			c.TABLE_SCHEMA,
						c.TABLE_NAME,
						c.ORDINAL_POSITION,
						c.COLUMN_NAME,
						c.DATA_TYPE,
						CASE
							WHEN c.DATA_TYPE IN ( N'binary', N'varbinary'                    ) THEN ( CASE c.CHARACTER_OCTET_LENGTH   WHEN -1 THEN N'(max)' ELSE CONCAT( N'(', c.CHARACTER_OCTET_LENGTH  , N')' ) END )
							WHEN c.DATA_TYPE IN ( N'char', N'varchar', N'nchar', N'nvarchar' ) THEN ( CASE c.CHARACTER_MAXIMUM_LENGTH WHEN -1 THEN N'(max)' ELSE CONCAT( N'(', c.CHARACTER_MAXIMUM_LENGTH, N')' ) END )
							WHEN c.DATA_TYPE IN ( N'datetime2', N'datetimeoffset'            ) THEN CONCAT( N'(', c.DATETIME_PRECISION, N')' )
							WHEN c.DATA_TYPE IN ( N'decimal', N'numeric'                     ) THEN CONCAT( N'(', c.NUMERIC_PRECISION , N',', c.NUMERIC_SCALE, N')' )
						END AS DATA_TYPE_PARAMETER,
						CASE c.IS_NULLABLE
							WHEN N'NO'  THEN N' NOT NULL'
							WHEN N'YES' THEN     N' NULL'
						END AS IS_NULLABLE2
		FROM			INFORMATION_SCHEMA.COLUMNS AS c
	)
	SELECT				q.TABLE_SCHEMA,
						q.TABLE_NAME,
						q.ORDINAL_POSITION,
						q.COLUMN_NAME,
						CONCAT( q.DATA_TYPE, ISNULL( q.DATA_TYPE_PARAMETER, N'' ), q.IS_NULLABLE2 ) AS FULL_DATA_TYPE,
						B.create_date,
						b.modify_date
	INTO				#TMP1
	FROM				q
	LEFT OUTER JOIN		sys.tables b ON q.TABLE_NAME = B.[name]
	WHERE				q.TABLE_NAME NOT IN ('charges07182021','database_firewall_rules','Query','Routes_DateTracker','ShippingPort_Data') -- Tables not required from DEV
	ORDER BY			q.TABLE_SCHEMA,q.TABLE_NAME,q.ORDINAL_POSITION;



IF OBJECT_ID('tempdb..#DATA1') is not null

	BEGIN
		DROP TABLE #DATA1
	END

	SELECT				ISNULL(A.TABLE_NAME,'')TABLE_NAME,'' COLUMN_NAME, '' DATA_TYPE
						,ISNULL(B.TABLE_NAME,'')TABLE_NAME1, '' COLUMN_NAME1,  '' DATA_TYPE1
						, 'TABLE Not in ' + @FromDB Remarks
	INTO				#DATA1
	FROM				(SELECT DISTINCT TABLE_NAME FROM #TMP1) A
	LEFT OUTER JOIN		(SELECT DISTINCT TABLE_NAME FROM #TESTDATAPROC) B ON A.TABLE_NAME = B.TABLE_NAME  
	WHERE				B.TABLE_NAME IS NULL



IF OBJECT_ID('tempdb..#DATA2') is not null

	BEGIN
		DROP TABLE #DATA2
	END

	BEGIN
		SELECT				ISNULL(B.TABLE_NAME,'')TABLE_NAME,'' COLUMN_NAME, '' DATA_TYPE
							,ISNULL(A.TABLE_NAME,'')TABLE_NAME1, '' COLUMN_NAME1,  '' DATA_TYPE1
							, 'TABLE Not in ' + @ToDB Remarks
		INTO				#DATA2
		FROM				(SELECT DISTINCT TABLE_NAME FROM #TESTDATAPROC) A
		LEFT OUTER JOIN		(SELECT DISTINCT TABLE_NAME FROM #TMP1) B ON A.TABLE_NAME = B.TABLE_NAME  
		WHERE				B.TABLE_NAME IS NULL
	END


DECLARE @TBL TABLE
	(
		TABLE_NAME VARCHAR(100),
		COLUMN_NAME VARCHAR(100),
		DATA_TYPE VARCHAR(100),
		CREATE_DATE	DATETIME,
		MODIFY_DATE DATETIME,
		TABLE_NAME1 VARCHAR(100),
		COLUMN_NAME1 VARCHAR(100),
		DATA_TYPE1 VARCHAR(100),
		CREATE_DATE1	DATETIME,
		MODIFY_DATE1 DATETIME,
		REMARKS VARCHAR(100)
	)

INSERT INTO			@TBL
SELECT				* 
FROM				(SELECT				ISNULL(A.TABLE_NAME,'')TABLE_NAME,ISNULL(A.COLUMN_NAME,'')COLUMN_NAME, ISNULL(A.FULL_DATA_TYPE,'')DATA_TYPE
										,ISNULL(A.CREATE_DATE,NULL) CREATE_DATE ,ISNULL(A.MODIFY_DATE,NULL) MODIFY_DATE
										,ISNULL(B.TABLE_NAME,'')TABLE_NAME1,ISNULL(B.COLUMN_NAME,'')COLUMN_NAME1, ISNULL(B.FULL_DATA_TYPE,'')DATA_TYPE1
										,ISNULL(B.CREATE_DATE,NULL) CREATE_DATE1 ,ISNULL(B.MODIFY_DATE,NULL) MODIFY_DATE1
										, 'Column Not in ' + @FromDB Remarks
					FROM				#TMP1 A
					LEFT OUTER JOIN		#TESTDATAPROC B ON A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME
					LEFT OUTER JOIN		#DATA1 C ON A.TABLE_NAME = C.TABLE_NAME 
					WHERE				B.COLUMN_NAME IS NULL AND C.TABLE_NAME IS NULL
					UNION ALL
					SELECT				ISNULL(B.TABLE_NAME,'')TABLE_NAME,ISNULL(B.COLUMN_NAME,'')COLUMN_NAME, ISNULL(B.FULL_DATA_TYPE,'')DATA_TYPE
										,ISNULL(B.CREATE_DATE,'') CREATE_DATE ,ISNULL(B.MODIFY_DATE,'') MODIFY_DATE
										,ISNULL(A.TABLE_NAME,'')TABLE_NAME,ISNULL(A.COLUMN_NAME,'')COLUMN_NAME, ISNULL(A.FULL_DATA_TYPE,'')DATA_TYPE
										,ISNULL(A.CREATE_DATE,'') CREATE_DATE1 ,ISNULL(A.MODIFY_DATE,'') MODIFY_DATE1
										, 'Column Not in ' + @ToDB Remarks
					FROM				#TESTDATAPROC A
					LEFT OUTER JOIN		#TMP1 B ON A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME
					LEFT OUTER JOIN		#DATA2 C ON A.TABLE_NAME = C.TABLE_NAME1 
					WHERE				B.COLUMN_NAME IS NULL  AND C.TABLE_NAME1 IS NULL
					UNION ALL
					SELECT				A.TABLE_NAME,A.COLUMN_NAME, A.FULL_DATA_TYPE, NULL,NUll
										,B.TABLE_NAME,B.COLUMN_NAME, B.FULL_DATA_TYPE, NULL, NULL
										, 'Difference in Data Type' Remarks
					FROM				#TMP1 A
					LEFT OUTER JOIN		#TESTDATAPROC B ON A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME
					WHERE				A.FULL_DATA_TYPE <> B.FULL_DATA_TYPE
					UNION ALL
					SELECT				TABLE_NAME,COLUMN_NAME,DATA_TYPE, B.create_date,B.modify_date,  TABLE_NAME1,COLUMN_NAME1,DATA_TYPE1,NULL,NULL,Remarks
					FROm				#DATA1 A
					LEFT OUTER JOIN		sys.tables B ON A.TABLE_NAME = B.[name]
					UNION ALL
					SELECT				TABLE_NAME,COLUMN_NAME,DATA_TYPE, NULL,NULL,  TABLE_NAME1,COLUMN_NAME1,DATA_TYPE1,B.create_date,b.modify_date,Remarks
					FROm				#DATA2 A
					LEFT OUTER JOIN		sys.tables B ON A.TABLE_NAME = B.[name]) A


DELETE FROM			@TBL
WHERE				TABLE_NAME IN ('DB_CompareData','DB_CheckDBChanges') OR TABLE_NAME1 IN ('DB_CompareData','DB_CheckDBChanges')


SELECT				*
INTO				#SysProc
FROM				sys.procedures 
WHERE				[name] NOT IN ('Scheduler_GetList_PRev20230927','Scheduler_GetDashBoard_Prev20230927','DispatchEntry_GetList_20230816')  -- Proc not required from Dev

DELETE FROM			DB_CheckDBChanges

INSERT INTO			DB_CheckDBChanges
SELECT * FROM		@TBL



INSERT INTO			DB_CheckDBChanges
SELECT				name,'','',A.create_date, A.modify_date, '','','',NULL,NULL,'Procedure Not in ' + @FromDB 
FROM				(SELECT * FROM #SysProc WHERE (NAME NOT LIKE '%_ASH%' AND NAME NOT LIKE '%_Shiv%'
					AND NAME NOT LIKE '%_old%' AND NAME NOT LIKE '%_sandeep%' AND NAME NOT LIKE '%_delete%'
					AND NAME NOT LIKE '%_PREV%' AND NAME NOT LIKE '%_Test%' AND NAME NOT LIKE '%UserInfo-old%'
					))  A
LEFT OUTER JOIN		(SELECT * FROM DB_CompareData WHERE ISPROC = 1 ) B ON A.name = B.TABLE_NAME 
WHERE				B.TABLE_NAME IS NULL AND A.create_date > GETDATE() - 60


INSERT INTO			DB_CheckDBChanges 
SELECT				'','','',NULL,NULL,A.TABLE_NAME,'','', A.create_date, A.modify_date,'Procedure Not in ' + @ToDB
FROM				(SELECT * FROM DB_CompareData WHERE ISPROC = 1 AND (TABLE_NAME NOT LIKE '%_ASH%' AND TABLE_NAME NOT LIKE '%_Shiv%'
					AND TABLE_NAME NOT LIKE '%_old%' AND TABLE_NAME NOT LIKE '%_sandeep%' AND TABLE_NAME NOT LIKE '%_delete%'
					AND TABLE_NAME NOT LIKE '%_Prev%' AND TABLE_NAME NOT LIKE '%_Test%'
					))  A
LEFT OUTER JOIN		#SysProc B ON A.TABLE_NAME = B.NAME 
WHERE				B.NAME IS NULL  AND A.create_date > GETDATE() - 60



SELECT * FROM		DB_CheckDBChanges

 


--SELECT				'1' TABLE_NAME, '2' COLUMN_NAME, '3' DATA_TYPE , '4' TABLE_NAME1, '5' COLUMN_NAME1, '6' DATA_TYPE1 , '7' REMARKS
--UNION ALL
--SELECT				'1' TABLE_NAME, '2' COLUMN_NAME, '3' DATA_TYPE , '4' TABLE_NAME, '5' COLUMN_NAME, '6' DATA_TYPE , '7' REMARKS


