


CREATE PROCEDURE [dbo].[DB_InsertCompareTables]

(
		@JSONData NVARCHAR(MAX) = ''
)

AS

BEGIN
	

	DELETE FROM DB_CompareData

	Create table #TestTable
	(
		 TABLE_SCHEMA			VARCHAR(100)
		,TABLE_NAME				VARCHAR(100)
		,ORDINAL_POSITION		VARCHAR(100)
		,COLUMN_NAME			VARCHAR(100)
		,FULL_DATA_TYPE			VARCHAR(100)
		,ISPROC					BIT
		,CREATE_DATE			DATETIME
		,MODIFY_DATE			DATETIME
		,DBNAME					VARCHAR(20)
	)

	INSERT INTO			#TestTable(TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION,COLUMN_NAME,FULL_DATA_TYPE,ISPROC,CREATE_DATE,MODIFY_DATE,DBname)
	SELECT				TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION,COLUMN_NAME,FULL_DATA_TYPE,ISPROC,CREATE_DATE,MODIFY_DATE,DBNAME
	FROM				OPENJSON(@JSONData,'$')
	With(
		 TABLE_SCHEMA			VARCHAR(100)	'$.TABLE_SCHEMA'
		,TABLE_NAME				VARCHAR(100)	'$.TABLE_NAME'
		,ORDINAL_POSITION		VARCHAR(100)	'$.ORDINAL_POSITION'
		,COLUMN_NAME			VARCHAR(100)	'$.COLUMN_NAME'
		,FULL_DATA_TYPE			VARCHAR(100)	'$.FULL_DATA_TYPE'
		,ISPROC					BIT				'$.ISPROC'
		,CREATE_DATE			DATETIME		'$.CREATE_DATE'
		,MODIFY_DATE			DATETIME		'$.MODIFY_DATE'
		,DBNAME					VARCHAR(20)		'$.DBNAME'
	)


	-- SELECT * FROM #TestTable

	INSERT INTO		DB_CompareData
					(TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION,COLUMN_NAME,FULL_DATA_TYPE,ISPROC,CREATE_DATE,MODIFY_DATE,DBNAME)
	SELECT			TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION,COLUMN_NAME,FULL_DATA_TYPE,ISPROC,CREATE_DATE,MODIFY_DATE, DBNAME
	FROM			#TestTable

	SELECT * FROM		DB_CompareData
	--INSERT INTO DB_CompareData
	--			(TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION,COLUMN_NAME,FULL_DATA_TYPE)
	--SELECT		@TABLE_SCHEMA,@TABLE_NAME,@ORDINAL_POSITION,@COLUMN_NAME,@FULL_DATA_TYPE

END

