CREATE PROCEDURE [dbo].[dependencies_sumantha] 
(
@TABLENAME VARCHAR(100) = ''
)
AS
BEGIN



SELECT		SC.NAME AS REFERENCING_SCHEMA_NAME,
			OB.NAME AS REFERENCING_ENTITY_NAME,
			OB.TYPE_DESC AS REFERENCING_ENTITY_TYPE,
			SC1.NAME AS REFERENCED_SCHEMA_NAME,
			OB1.NAME AS REFERENCED_ENTITY_NAME,
			OB1.TYPE_DESC AS REFERENCED_ENTITY_TYPE

INTO #DEPEND

FROM		SYS.SQL_EXPRESSION_DEPENDENCIES AS SED

INNER JOIN	SYS.OBJECTS AS OB ON SED.REFERENCING_ID = OB.OBJECT_ID
INNER JOIN	SYS.SCHEMAS AS SC ON OB.SCHEMA_ID = SC.SCHEMA_ID
INNER JOIN	SYS.OBJECTS AS OB1 ON SED.REFERENCED_ID = OB1.OBJECT_ID
INNER JOIN	SYS.SCHEMAS AS SC1 ON OB1.SCHEMA_ID = SC1.SCHEMA_ID

WHERE		OB1.NAME = @TABLENAME

INSERT INTO #DEPEND
			(REFERENCING_SCHEMA_NAME, REFERENCING_ENTITY_NAME, REFERENCING_ENTITY_TYPE, REFERENCED_SCHEMA_NAME, REFERENCED_ENTITY_NAME, REFERENCED_ENTITY_TYPE)
SELECT				SC.NAME,				T.NAME,					OB.TYPE_DESC,				SC1.NAME,				OB1.NAME,			OB1.TYPE_DESC
FROM	SYS.TRIGGERS T

INNER JOIN	SYS.OBJECTS OB ON T.OBJECT_ID = OB.OBJECT_ID
INNER JOIN	SYS.SCHEMAS AS SC ON OB.SCHEMA_ID = SC.SCHEMA_ID
INNER JOIN	SYS.OBJECTS AS OB1 ON T.PARENT_ID = OB1.OBJECT_ID
INNER JOIN	SYS.SCHEMAS AS SC1 ON OB1.SCHEMA_ID = SC1.SCHEMA_ID

WHERE	OB1.NAME = @TABLENAME

SELECT DISTINCT * FROM #DEPEND
ORDER BY REFERENCING_ENTITY_NAME

DROP TABLE #DEPEND

END