CREATE TABLE [dbo].[BaseInfo_WRK] (
    [InvoiceKey]         INT           NULL,
    [InvoiceNo]          VARCHAR (50)  NULL,
    [InvoiceDate]        DATE          NULL,
    [OrderDetailKey]     INT           NULL,
    [OrderType]          VARCHAR (100) NULL,
    [ContainerNo]        VARCHAR (20)  NULL,
    [Routekey]           INT           NULL,
    [LegID]              VARCHAR (50)  NULL,
    [FromLocation]       VARCHAR (50)  NULL,
    [ToLocation]         VARCHAR (50)  NULL,
    [SourceAddrKey]      INT           NULL,
    [DestinationAddrKey] INT           NULL,
    [ShortName]          VARCHAR (20)  NULL,
    [YardType]           VARCHAR (20)  NULL,
    [YardID]             INT           NULL,
    [ShippingPortKey]    INT           NULL,
    [ShippingPortID]     VARCHAR (50)  NULL,
    [City]               VARCHAR (MAX) NULL,
    [State]              VARCHAR (MAX) NULL,
    [ZipCode]            VARCHAR (50)  NULL,
    [DriverKey]          INT           NULL,
    [DriverID]           VARCHAR (20)  NULL,
    [TruckType]          VARCHAR (100) NULL,
    [LegCostType]        VARCHAR (3)   NULL,
    [LegTypeName]        VARCHAR (50)  NULL,
    [IsDryRun]           BIT           NULL,
    [DryRunTypeKey]      INT           NULL,
    [DryRunType]         VARCHAR (100) NULL,
    [IsBobtail]          BIT           NULL,
    [LegNo]              INT           NULL,
    [ChassisCategoryKey] INT           NULL,
    [LocationName]       VARCHAR (MAX) NULL,
    [Address1]           VARCHAR (MAX) NULL
);

