CREATE TABLE [dbo].[Data_InvoiceReport_PRAVEEN] (
    [InvoiceKey]      BIGINT          NOT NULL,
    [InvoiceNo]       VARCHAR (50)    NOT NULL,
    [InvoiceDate]     DATETIME        NOT NULL,
    [STATUS]          VARCHAR (200)   NOT NULL,
    [StatusKey]       SMALLINT        NOT NULL,
    [CustKey]         INT             NULL,
    [CustID]          VARCHAR (100)   NOT NULL,
    [CustName]        VARCHAR (100)   NOT NULL,
    [OrderNo]         VARCHAR (50)    NULL,
    [ContainerCount]  INT             NULL,
    [DestinationCity] VARCHAR (255)   NULL,
    [BrokerRefNo]     VARCHAR (50)    NOT NULL,
    [InvoiceAmount]   DECIMAL (20, 4) NULL,
    [OverDueDays]     INT             NULL,
    [NetDue]          DECIMAL (38, 2) NULL,
    [Payments]        DECIMAL (38, 2) NOT NULL,
    [Credit]          DECIMAL (38, 2) NOT NULL,
    [Balance]         DECIMAL (38, 2) NULL,
    [InvoiceType]     VARCHAR (7)     NOT NULL,
    [Containers]      NVARCHAR (MAX)  NULL,
    [CsrKey]          INT             NOT NULL,
    [CsrName]         VARCHAR (1)     NOT NULL,
    [InvoicerName]    VARCHAR (50)    NOT NULL,
    [CompleteDate]    DATE            NULL,
    [CreateUserKey]   INT             NULL,
    [ProcesDate]      DATETIME        NULL,
    [BookingNo]       VARCHAR (50)    NULL
);

