CREATE TABLE [dbo].[DB_CheckDBChanges] (
    [TABLE_NAME]   VARCHAR (100) NULL,
    [COLUMN_NAME]  VARCHAR (100) NULL,
    [DATA_TYPE]    VARCHAR (100) NULL,
    [CREATE_DATE]  DATETIME      NULL,
    [MODIFY_DATE]  DATETIME      NULL,
    [TABLE_NAME1]  VARCHAR (100) NULL,
    [COLUMN_NAME1] VARCHAR (100) NULL,
    [DATA_TYPE1]   VARCHAR (100) NULL,
    [CREATE_DATE1] DATETIME      NULL,
    [MODIFY_DATE1] DATETIME      NULL,
    [REMARKS]      VARCHAR (100) NULL
);

