CREATE TABLE [dbo].[DryVanRemoved_20241014] (
    [OrderExpenseKey]            INT             IDENTITY (1, 1) NOT NULL,
    [Itemkey]                    INT             NOT NULL,
    [RouteKey]                   INT             NOT NULL,
    [UnitCost]                   DECIMAL (18, 5) NULL,
    [Qty]                        DECIMAL (18, 5) NULL,
    [NewUnitCost]                DECIMAL (18, 5) NULL,
    [DateFrom]                   DATETIME        NULL,
    [DateTo]                     DATETIME        NULL,
    [CreateDate]                 DATETIME        NOT NULL,
    [CreateUserKey]              INT             NOT NULL,
    [LastUpdateDate]             DATETIME        NULL,
    [UpdateUserKey]              INT             NULL,
    [ExpenseItemKey]             INT             NULL,
    [TimeDuration]               VARCHAR (10)    NULL,
    [InternalNotes]              NVARCHAR (MAX)  NULL,
    [PvsNP]                      VARCHAR (5)     NULL,
    [IsCSRApproved]              BIT             NULL,
    [IsCustomerApproved]         BIT             NULL,
    [FreeTime]                   INT             NULL,
    [BvsNB]                      BIT             NULL,
    [MinCnt]                     INT             NULL,
    [MaxCnt]                     INT             NULL,
    [CustomerRate]               DECIMAL (18, 4) NULL,
    [ChargeSource]               VARCHAR (20)    NULL,
    [isCSApproved]               BIT             NULL,
    [CSApprovedDate]             DATETIME        NULL,
    [CSUserKey]                  INT             NULL,
    [WarehouseItemKey]           INT             NULL,
    [IsInvoiced]                 BIT             NULL,
    [OrderDetailKey]             INT             NULL,
    [IsChargeSharedWithCustomer] BIT             NULL,
    [ChargeSharedWithCustBy]     INT             NULL,
    [ChargeSharedWithCustDate]   DATETIME        NULL,
    [IsCustomerApprovedCharge]   BIT             NULL,
    [CustomerApprovedChargeBy]   INT             NULL,
    [CustomerApprovedChargeDate] DATETIME        NULL
);

