CREATE TABLE [dbo].[Gnosis_Export_BookingDetails_Final] (
    [uuid]                       VARCHAR (50)   NULL,
    [booking_number]             VARCHAR (20)   NULL,
    [num_of_supplier_containers] VARCHAR (20)   NULL,
    [num_containers]             VARCHAR (20)   NULL,
    [por_cargo_cut_off_dt]       VARCHAR (20)   NULL,
    [por_early_receive_dt]       VARCHAR (20)   NULL,
    [cargo_cut_off_dt]           VARCHAR (20)   NULL,
    [doc_cut_off]                VARCHAR (100)  NULL,
    [early_receive_dt]           VARCHAR (20)   NULL,
    [first_vessel]               VARCHAR (200)  NULL,
    [first_voyage]               VARCHAR (20)   NULL,
    [vessel_etb_pol_dt]          VARCHAR (20)   NULL,
    [vessel_eta_pol_dt]          VARCHAR (20)   NULL,
    [vessel_etd_pol_dt]          VARCHAR (20)   NULL,
    [pol_locode]                 VARCHAR (20)   NULL,
    [pol_city]                   VARCHAR (20)   NULL,
    [pol_terminal_name]          VARCHAR (100)  NULL,
    [pol_terminal_firms_code]    VARCHAR (20)   NULL,
    [cancelled]                  VARCHAR (20)   NULL,
    [custom_columns]             NVARCHAR (MAX) NULL,
    [containers]                 NVARCHAR (MAX) NULL,
    [carrier_scac]               VARCHAR (20)   NULL,
    [carrier_name]               VARCHAR (10)   NULL,
    [carrier_type]               VARCHAR (20)   NULL,
    [CreatedDate]                DATETIME       NULL
);

