CREATE TABLE [dbo].[IH_20251023] (
    [InvoiceKey]             INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceNo]              VARCHAR (50)    NOT NULL,
    [InvoiceDate]            DATE            NOT NULL,
    [CustKey]                INT             NOT NULL,
    [BillToAddrKey]          INT             NOT NULL,
    [InvoiceAmount]          DECIMAL (18, 2) NOT NULL,
    [DueDate]                DATE            NOT NULL,
    [InvoiceType]            SMALLINT        NULL,
    [CompanyKey]             SMALLINT        NULL,
    [StatusKey]              SMALLINT        NOT NULL,
    [CreateUserKey]          INT             NOT NULL,
    [IsInvoiceApproved]      BIT             NULL,
    [IsPaymentReceived]      BIT             NULL,
    [CreateDate]             DATETIME        NOT NULL,
    [UpdateUserKey]          INT             NULL,
    [UpdateDate]             DATETIME        NULL,
    [InvoiceApprovedUserKey] INT             NULL,
    [InvoiceApprovedDate]    DATETIME        NULL,
    [OrderKey]               INT             NULL,
    [CustomerNote]           VARCHAR (3000)  NULL,
    [InternalNote]           VARCHAR (3000)  NULL,
    [IsPrinted]              BIT             NULL,
    [PrintedUserKey]         INT             NULL,
    [PrintedDate]            DATETIME        NULL,
    [PaymentRecdUserKey]     INT             NULL,
    [PaymentRecdDate]        DATETIME        NULL,
    [IsRevised]              BIT             NULL,
    [RevisionDate]           DATETIME        NULL,
    [RevisionUserKey]        INT             NULL,
    [BrokerRefNo]            VARCHAR (50)    NULL,
    [InvoiceCompanyKey]      INT             NULL,
    [DestinationAddrKey]     INT             NULL,
    [ReasoncodeKey]          INT             NULL,
    [CustApproved]           BIT             NULL,
    [AprovedReasonCodeKey]   INT             NULL
);

