CREATE TABLE [dbo].[Item] (
    [ItemKey]            INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ItemID]             VARCHAR (30)    NULL,
    [Description]        VARCHAR (255)   NULL,
    [ItemTypeKey]        SMALLINT        NULL,
    [UnitCost]           DECIMAL (18, 2) NULL,
    [StatusKey]          SMALLINT        CONSTRAINT [DF_Item_StatusKey] DEFAULT ((1)) NULL,
    [CompanyKey]         SMALLINT        CONSTRAINT [DF_Item_CompnayKey] DEFAULT ((1)) NULL,
    [PriceBasisKey]      SMALLINT        NULL,
    [CreateDate]         DATETIME        NULL,
    [StatusDate]         DATETIME        NULL,
    [CategoryKey]        SMALLINT        NULL,
    [InvoiceItemDesc]    VARCHAR (255)   NULL,
    [EDICode]            VARCHAR (3)     NULL,
    [ItemTypeMappingKey] INT             NULL,
    [CostGrp]            INT             NULL,
    [InternalCost]       DECIMAL (18, 5) NULL,
    [itemDescrOld]       VARCHAR (255)   NULL,
    [Remarks]            VARCHAR (100)   NULL,
    [ItemCostGroup]      VARCHAR (100)   NULL,
    [MasterItemKey]      INT             NULL,
    [DryRunType]         VARCHAR (50)    NULL,
    [PrevItemTypeKey]    INT             NULL,
    CONSTRAINT [Item_pkey] PRIMARY KEY CLUSTERED ([ItemKey] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Item_Company] FOREIGN KEY ([CompanyKey]) REFERENCES [dbo].[Company] ([CompanyKey]),
    CONSTRAINT [FK_Item_ItemPriceBasis] FOREIGN KEY ([PriceBasisKey]) REFERENCES [dbo].[ItemPriceBasis] ([PriceBasisKey]),
    CONSTRAINT [FK_Item_Status] FOREIGN KEY ([StatusKey]) REFERENCES [dbo].[Status] ([StatusKey])
);

