CREATE TABLE [dbo].[ManualInvoiceHeader_Deleted_2023_01_14] (
    [MInvoiceKey]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [MInvoiceNo]          VARCHAR (20)    NULL,
    [MInvoiceDate]        DATETIME        NOT NULL,
    [MInvoiceAmount]      DECIMAL (18, 4) NULL,
    [OrderKey]            INT             NULL,
    [CustomerKey]         INT             NULL,
    [BillToAddressKey]    INT             NULL,
    [MInvoiceSentDate]    DATETIME        NULL,
    [MInvoiceConfirmDate] DATETIME        NULL,
    [CreatedDate]         DATETIME        NULL,
    [CreatedUserKey]      INT             NULL,
    [UpdateDate]          DATETIME        NULL,
    [UpdatedUserKey]      INT             NULL,
    [OrderNo]             VARCHAR (50)    NULL,
    [StatusKey]           INT             NULL,
    [InternalNotes]       VARCHAR (2000)  NULL,
    [CustomerNotes]       VARCHAR (2000)  NULL,
    [RevisionDate]        DATETIME        NULL,
    [RevisionUserKey]     INT             NULL,
    [InternalNote]        VARCHAR (MAX)   NULL,
    [PreVoidStatusKey]    INT             NULL,
    [VoidedDate]          DATETIME        NULL,
    [IsVoid]              BIT             NULL,
    [VoidedUserKey]       INT             NULL,
    [BrokerRef]           VARCHAR (50)    NULL,
    [SteamShipLineKey]    INT             NULL,
    [SteamShipLineRef]    VARCHAR (100)   NULL,
    [OriginalInvoiceNo]   VARCHAR (50)    NULL,
    [InvoiceCompanyKey]   INT             NULL
);

