CREATE TABLE [dbo].[ODS_Temp_20250623] (
    [OrderDetailStopKey]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [OrderDetailKey]                INT           NOT NULL,
    [OrderStopKey]                  BIGINT        NULL,
    [StopTypeKey]                   SMALLINT      NULL,
    [StopName]                      VARCHAR (100) NULL,
    [StopNameSetUserKey]            INT           NULL,
    [StopNameSetDateTime]           DATETIME      NULL,
    [StopAddrKey]                   INT           NULL,
    [StopNumber]                    SMALLINT      NULL,
    [LocationType]                  VARCHAR (20)  NULL,
    [SchedulePickupDate]            DATETIME      NULL,
    [SchedulePickupUserKey]         INT           NULL,
    [SchedulePickupSetDateTime]     DATETIME      NULL,
    [SchedulePickupDateTo]          DATETIME      NULL,
    [SchedulePickupToUserKey]       DATETIME      NULL,
    [SchedulePickupToSetDateTime]   DATETIME      NULL,
    [ActualPickupDate]              DATETIME      NULL,
    [ActualPickupUserKey]           INT           NULL,
    [ActualPickupSetDateTime]       DATETIME      NULL,
    [ScheduleDeliveryDate]          DATETIME      NULL,
    [ScheduleDeliveryUserKey]       INT           NULL,
    [ScheduleDeliverySetDateTime]   DATETIME      NULL,
    [ScheduleDeliveryDateTo]        DATETIME      NULL,
    [ScheduleDeliveryToUserKey]     DATETIME      NULL,
    [ScheduleDeliveryToSetDateTime] DATETIME      NULL,
    [ActualDeliveryDate]            DATETIME      NULL,
    [ActualDeliveryUserKey]         INT           NULL,
    [ActualDeliverySetDateTime]     DATETIME      NULL,
    [ToRouteKey]                    INT           NULL,
    [FromRouteKey]                  INT           NULL,
    [StatusKey]                     SMALLINT      NULL,
    [CreateDate]                    DATETIME      NULL,
    [CreateUserKey]                 INT           NULL,
    [UpdateDate]                    DATETIME      NULL,
    [UpdateUserKey]                 INT           NULL,
    [IsDryRunPort]                  BIT           NULL,
    [DryRunPortSetDateTime]         DATETIME      NULL,
    [DryRunPortSetUserKey]          INT           NULL,
    [IsDryRunCustomer]              BIT           NULL,
    [DryRunCustomerSetDateTime]     DATETIME      NULL,
    [DryRunCustomerSetUserKey]      INT           NULL,
    [RefNo]                         VARCHAR (50)  NULL,
    [IsTMFChecked]                  BIT           NULL,
    [IsCTFChecked]                  BIT           NULL,
    [TMFCheckUserKey]               INT           NULL,
    [CTFCheckUserKey]               INT           NULL,
    [TMFCheckDate]                  DATETIME      NULL,
    [CTFCheckDate]                  DATETIME      NULL,
    [ReasonCode]                    INT           NULL,
    [DropOrLive]                    CHAR (1)      NULL,
    [DropOrLiveSetUserKey]          INT           NULL,
    [DropOrLiveSetDatetime]         DATETIME      NULL,
    [ExceptionReasonCode]           INT           NULL,
    [ExceptionRCSetUserKey]         INT           NULL,
    [ExceptionRCSetDateTime]        DATETIME      NULL,
    [IsDeleted]                     BIT           NULL,
    [DeleteUserKey]                 INT           NULL,
    [DeleteDate]                    DATETIME      NULL,
    [IsBobTail]                     BIT           NULL,
    [BobtailSetDateTime]            DATETIME      NULL,
    [BobtailSetUserKey]             INT           NULL,
    [IsEmpty]                       BIT           NULL,
    [EmptySetDateTime]              DATETIME      NULL,
    [EmptySetUserKey]               INT           NULL,
    [IsStreetTurn]                  BIT           NULL,
    [StreetSturnSetDateTime]        DATETIME      NULL,
    [StreetSturnSetUserKey]         INT           NULL,
    [IsChassisSplit]                BIT           NULL,
    [ChassisSplitSetDateTime]       DATETIME      NULL,
    [ChassisSplitSetUserKey]        INT           NULL,
    [Is247Pickup]                   BIT           NULL,
    [Is247PickupMarkedby]           INT           NULL,
    [Is247PickupMarkedDate]         DATETIME      NULL,
    [Is247Delivery]                 BIT           NULL,
    [Is247DeliveryMarkedBy]         INT           NULL,
    [Is247DeliveryMarkedDate]       DATETIME      NULL,
    [StopIndex]                     INT           NULL
);

