CREATE TABLE [dbo].[OrderHeader_BKP20280130] (
    [OrderKey]             INT             IDENTITY (1, 1) NOT NULL,
    [OrderNo]              VARCHAR (20)    NOT NULL,
    [OrderDate]            DATE            NOT NULL,
    [CustKey]              INT             NOT NULL,
    [BillToAddrKey]        INT             NULL,
    [BillToCopyAddrKey]    INT             NULL,
    [SourceAddrKey]        INT             NULL,
    [DestinationAddrKey]   INT             NULL,
    [ReturnAddrKey]        INT             NULL,
    [SourceKey]            INT             NULL,
    [OrderTypeKey]         SMALLINT        NOT NULL,
    [Status]               SMALLINT        NULL,
    [StatusDate]           DATETIME2 (7)   NULL,
    [HoldReasonKey]        SMALLINT        NULL,
    [HoldDate]             DATETIME2 (7)   NULL,
    [BrokerKey]            INT             NULL,
    [BrokerRefNo]          VARCHAR (50)    NULL,
    [PortoForiginKey]      INT             NULL,
    [CarrierKey]           INT             NULL,
    [VesselName]           VARCHAR (50)    NULL,
    [BillOfLading]         VARCHAR (50)    NULL,
    [BookingNo]            VARCHAR (50)    NULL,
    [IsHazardous]          BIT             NULL,
    [IsOverWeight]         BIT             NULL,
    [IsTriaxle]            BIT             NULL,
    [NeedsTobeScaled]      BIT             NULL,
    [PriorityKey]          SMALLINT        NULL,
    [CreateDate]           DATETIME2 (7)   NULL,
    [Ach_Enabled]          BIT             NOT NULL,
    [Ach_Amount]           DECIMAL (18, 2) NULL,
    [CreateUserKey]        INT             NULL,
    [LastUpdateDate]       DATETIME2 (7)   NULL,
    [LastUpdateUserKey]    INT             NULL,
    [PortofDestinationKey] INT             NULL,
    [ConsigneeAddrKey]     INT             NULL,
    [CompanyKey]           SMALLINT        NOT NULL,
    [CsrKey]               INT             NULL,
    [CommentKey]           INT             NULL,
    [ETADate]              DATETIME2 (7)   NULL,
    [BaseRateAmount]       DECIMAL (18, 2) NULL,
    [SalesPersonKey]       INT             NULL,
    [ReleaseNo]            VARCHAR (10)    NULL,
    [IntegrationWONo]      VARCHAR (100)   NULL,
    [CSRManagerKey]        INT             NULL,
    [OrderSource]          VARCHAR (20)    NULL,
    [MarketLocationKey]    INT             NULL,
    [Consignee]            VARCHAR (100)   NULL,
    [SteamShipLinekey]     INT             NULL,
    [SenderInfo]           VARCHAR (100)   NULL
);

