CREATE TABLE [dbo].[OrderdetailTemp_Praveen] (
    [OrderDetailKey]           INT             IDENTITY (1, 1) NOT NULL,
    [OrderKey]                 INT             NOT NULL,
    [ContainerNo]              VARCHAR (20)    NOT NULL,
    [ConfirmationNo]           VARCHAR (30)    NULL,
    [ContainerSizeKey]         SMALLINT        NOT NULL,
    [Chassis]                  VARCHAR (20)    NULL,
    [SealNo]                   VARCHAR (20)    NOT NULL,
    [Weight]                   DECIMAL (18, 2) NULL,
    [ApptDateFrom]             DATE            NULL,
    [ApptDateTo]               DATE            NULL,
    [Status]                   SMALLINT        NULL,
    [StatusDate]               DATETIME        NULL,
    [HoldReasonKey]            SMALLINT        NULL,
    [LastFreeDay]              DATETIME        NULL,
    [HoldDate]                 DATETIME        NULL,
    [ReturnDate]               DATE            NULL,
    [ReturnTime]               TIME (7)        NULL,
    [PickupTime]               VARCHAR (8)     NULL,
    [DropOffTime]              VARCHAR (8)     NULL,
    [PickupDate]               DATETIME        NULL,
    [DropOffDate]              DATETIME        NULL,
    [CutOffDate]               DATETIME        NULL,
    [RouteKey]                 INT             NULL,
    [ActualPickupTime]         VARCHAR (8)     NULL,
    [ActualDropOffTime]        VARCHAR (8)     NULL,
    [ActualPickupDate]         DATETIME        NULL,
    [ActualDropOffDate]        DATETIME        NULL,
    [ContainerID]              VARCHAR (50)    NULL,
    [IsHazardus]               BIT             NULL,
    [IsOverWeight]             BIT             NULL,
    [IsTriaxle]                BIT             NULL,
    [NeedtobeScaled]           BIT             NULL,
    [CommentKey]               INT             NULL,
    [CreateUserKey]            INT             NULL,
    [UpdateUserKey]            INT             NULL,
    [SourceAddrKey]            INT             NULL,
    [DestinationAddrKey]       INT             NULL,
    [CreateDate]               DATETIME        NULL,
    [LastUpdateDate]           DATETIME        NULL,
    [LegTypeKey]               SMALLINT        NULL,
    [WeightUnit]               SMALLINT        NULL,
    [IsEmpty]                  BIT             NULL,
    [DriverNotes]              VARCHAR (1000)  NULL,
    [SchedulerNotes]           VARCHAR (1000)  NULL,
    [IsTMF]                    BIT             NULL,
    [CompleteDate]             DATETIME        NULL,
    [VesselETA]                DATETIME        NULL,
    [isStreetTurn]             BIT             NULL,
    [StreetTurnSetUser]        INT             NULL,
    [StreetTurnSetDate]        DATETIME        NULL,
    [IsLinked]                 BIT             NULL,
    [LinkedContainerNo]        VARCHAR (20)    NULL,
    [LinkedOrderDetailKey]     INT             NULL,
    [ContainerStatusKey]       SMALLINT        NULL,
    [CurrentRouteKey]          INT             NULL,
    [TotalLegs]                SMALLINT        NULL,
    [CurrentLegNo]             SMALLINT        NULL,
    [OpenLegs]                 SMALLINT        NULL,
    [TMFCheckOff]              BIT             NULL,
    [CTFCheckOff]              BIT             NULL,
    [SizeCheckOff]             BIT             NULL,
    [MarkedNoEmptyAvailable]   BIT             NULL,
    [MarkedNoEmptyAvailableBY] INT             NULL,
    [PUDelayedCodeKEy]         INT             NULL,
    [PrepullDelayedCodeKEy]    INT             NULL,
    [isWhseChargesConfirmed]   BIT             NULL,
    [WhseChargeApprovedby]     INT             NULL,
    [WhseChargeApprovedDate]   DATETIME        NULL,
    [isCSChargeConfirmed]      BIT             NULL,
    [CSChargeConfirmedBy]      INT             NULL,
    [CSChargeConfirmedDate]    DATETIME        NULL,
    [isChargesSharedWithCust]  BIT             NULL,
    [ChargeSharedWithCustBy]   INT             NULL,
    [ChargeSharedWithCustDate] DATETIME        NULL,
    [isCustApprovedCharges]    BIT             NULL
);

