CREATE TABLE [dbo].[OrderDetail_Deleted] (
    [OrderDetailKey]           INT             IDENTITY (1, 1) NOT NULL,
    [OrderKey]                 INT             NOT NULL,
    [ContainerNo]              VARCHAR (20)    NOT NULL,
    [ConfirmationNo]           VARCHAR (30)    NULL,
    [ContainerSizeKey]         SMALLINT        NOT NULL,
    [Chassis]                  VARCHAR (20)    NULL,
    [SealNo]                   VARCHAR (20)    NULL,
    [Weight]                   DECIMAL (18, 2) NULL,
    [ApptDateFrom]             DATE            NULL,
    [ApptDateTo]               DATE            NULL,
    [Status]                   SMALLINT        NULL,
    [StatusDate]               DATETIME        NULL,
    [HoldReasonKey]            SMALLINT        NULL,
    [LastFreeDay]              DATETIME        NULL,
    [HoldDate]                 DATETIME        NULL,
    [ReturnDate]               DATE            NULL,
    [ReturnTime]               TIME (7)        NULL,
    [PickupTime]               VARCHAR (8)     NULL,
    [DropOffTime]              VARCHAR (8)     NULL,
    [PickupDate]               DATETIME        NULL,
    [DropOffDate]              DATETIME        NULL,
    [CutOffDate]               DATETIME        NULL,
    [RouteKey]                 INT             NULL,
    [ActualPickupTime]         VARCHAR (8)     NULL,
    [ActualDropOffTime]        VARCHAR (8)     NULL,
    [ActualPickupDate]         DATETIME        NULL,
    [ActualDropOffDate]        DATETIME        NULL,
    [ContainerID]              VARCHAR (50)    NULL,
    [IsHazardus]               BIT             NULL,
    [IsOverWeight]             BIT             NULL,
    [IsTriaxle]                BIT             NULL,
    [NeedtobeScaled]           BIT             NULL,
    [CommentKey]               INT             NULL,
    [CreateUserKey]            INT             NULL,
    [UpdateUserKey]            INT             NULL,
    [SourceAddrKey]            INT             NULL,
    [DestinationAddrKey]       INT             NULL,
    [CreateDate]               DATETIME        NULL,
    [LastUpdateDate]           DATETIME        NULL,
    [LegTypeKey]               SMALLINT        NULL,
    [WeightUnit]               SMALLINT        NULL,
    [IsEmpty]                  BIT             NULL,
    [DriverNotes]              VARCHAR (1000)  NULL,
    [SchedulerNotes]           VARCHAR (1000)  NULL,
    [IsTMF]                    BIT             NULL,
    [CompleteDate]             DATETIME        NULL,
    [VesselETA]                DATETIME        NULL,
    [isStreetTurn]             BIT             NULL,
    [StreetTurnSetUser]        INT             NULL,
    [StreetTurnSetDate]        DATETIME        NULL,
    [IsLinked]                 BIT             NULL,
    [LinkedContainerNo]        VARCHAR (20)    NULL,
    [LinkedOrderDetailKey]     INT             NULL,
    [ContainerStatusKey]       SMALLINT        NULL,
    [CurrentRouteKey]          INT             NULL,
    [TotalLegs]                SMALLINT        NULL,
    [CurrentLegNo]             SMALLINT        NULL,
    [OpenLegs]                 SMALLINT        NULL,
    [TMFCheckOff]              BIT             NULL,
    [CTFCheckOff]              BIT             NULL,
    [SizeCheckOff]             BIT             NULL,
    [MarkedNoEmptyAvailable]   BIT             NULL,
    [MarkedNoEmptyAvailableBY] INT             NULL,
    [PUDelayedCodeKEy]         INT             NULL,
    [PrepullDelayedCodeKEy]    INT             NULL,
    [isWhseChargesConfirmed]   BIT             NULL,
    [WhseChargeApprovedby]     INT             NULL,
    [WhseChargeApprovedDate]   DATETIME        NULL,
    [isCSChargeConfirmed]      BIT             NULL,
    [CSChargeConfirmedBy]      INT             NULL,
    [CSChargeConfirmedDate]    DATETIME        NULL,
    [isChargesSharedWithCust]  BIT             NULL,
    [ChargeSharedWithCustBy]   INT             NULL,
    [ChargeSharedWithCustDate] DATETIME        NULL,
    [isCustApprovedCharges]    BIT             NULL,
    [IsTMFJCTPaid]             BIT             NULL,
    [IsTMFCustomerPaid]        BIT             NULL,
    [IsCTFJCTPaid]             BIT             NULL,
    [IsCTFCustomerPaid]        BIT             NULL,
    [TMFMarkDate]              DATETIME        NULL,
    [CTFMarkDate]              DATETIME        NULL,
    [ContainerNoSource]        VARCHAR (100)   NULL,
    [ContainerNoDate]          DATETIME        NULL,
    [ContainerNoUser]          INT             NULL,
    [Consignee]                NVARCHAR (200)  NULL,
    [ReturnToStopKey]          INT             NULL,
    [StopOffA_StopKey]         INT             NULL,
    [OrderTypeKey]             SMALLINT        NULL,
    [StopOffB_StopKey]         INT             NULL,
    [CustRefNo]                VARCHAR (50)    NULL,
    [PriorityKey]              INT             NULL,
    [BookingNo]                VARCHAR (50)    NULL,
    [ShipFromStopKey]          INT             NULL,
    [CSRKey]                   INT             NULL,
    [ShipToStopKey]            INT             NULL,
    [JCTPaidDemurrage]         BIT             NULL,
    [DropOrLive]               VARCHAR (5)     NULL,
    [StopOffD_StopKey]         INT             NULL,
    [StopOffC_StopKey]         INT             NULL,
    [BillOfLadding]            VARCHAR (50)    NULL,
    [AvailableT]               BIT             NULL,
    [AvailableTSetUserKey]     INT             NULL,
    [AvailableTSetDateTime]    DATETIME        NULL,
    [ScheduleT]                BIT             NULL,
    [ScheduleTSetUserKey]      INT             NULL,
    [ScheduleTSetDateTime]     DATETIME        NULL,
    [DemCheck]                 BIT             NULL,
    [DemCheckSetUserKey]       INT             NULL,
    [DemCheckSetDateTime]      DATETIME        NULL,
    [Issues]                   BIT             NULL,
    [IssuesSetUserKey]         INT             NULL,
    [IssuesSetDateTime]        DATETIME        NULL,
    [SenderInfo]               VARCHAR (300)   NULL
);

