CREATE TABLE [dbo].[OrderListData] (
    [OrderNo]               VARCHAR (20)  NOT NULL,
    [OrderDate]             DATE          NOT NULL,
    [CustKey]               INT           NOT NULL,
    [BillToAddressKey]      INT           NULL,
    [BillToAddrName]        VARCHAR (100) NULL,
    [SourceAddressKey]      INT           NULL,
    [SourceAddrName]        VARCHAR (255) NULL,
    [DestinationAddressKey] INT           NULL,
    [DestinationAddrName]   VARCHAR (255) NULL,
    [ReturnAddressKey]      INT           NULL,
    [OrderTypeKey]          SMALLINT      NOT NULL,
    [PriorityKey]           SMALLINT      NULL,
    [Status]                SMALLINT      NULL,
    [StatusDate]            DATETIME2 (7) NULL,
    [HoldReason]            VARCHAR (255) NULL,
    [HoldDate]              DATETIME2 (7) NULL,
    [BrokerName]            VARCHAR (255) NULL,
    [BrokerID]              VARCHAR (20)  NULL,
    [BrokerKey]             INT           NULL,
    [BrokerRefNo]           VARCHAR (50)  NULL,
    [PortoForiginKey]       INT           NULL,
    [CarrierKey]            INT           NULL,
    [VesselName]            VARCHAR (50)  NULL,
    [BillOfLading]          VARCHAR (50)  NULL,
    [BookingNo]             VARCHAR (50)  NULL,
    [CreateDate]            DATETIME2 (7) NULL,
    [CreateUserKey]         INT           NULL,
    [OrderKey]              INT           NOT NULL,
    [ETADate]               DATETIME2 (7) NULL,
    [OrderTypeDescription]  VARCHAR (100) NULL,
    [StatusDescription]     VARCHAR (200) NULL,
    [NextAction]            VARCHAR (1)   NOT NULL,
    [ContainerCount]        INT           NULL,
    [PickupLocation]        VARCHAR (255) NULL,
    [DeliveryLocation]      VARCHAR (255) NULL,
    [CustName]              VARCHAR (100) NULL,
    [CusAddress1]           VARCHAR (255) NULL,
    [CusAddress2]           VARCHAR (255) NULL,
    [CusAddrName]           VARCHAR (255) NULL,
    [CusCity]               VARCHAR (255) NULL,
    [CusCountry]            CHAR (3)      NULL,
    [CusEmail]              VARCHAR (255) NULL,
    [CusEmail2]             VARCHAR (50)  NULL,
    [CusFax]                VARCHAR (20)  NULL,
    [CusState]              VARCHAR (255) NULL,
    [CusZipCode]            VARCHAR (50)  NULL,
    [SRAddress1]            VARCHAR (255) NULL,
    [SRAddress2]            VARCHAR (255) NULL,
    [SRAddrName]            VARCHAR (255) NULL,
    [SRCity]                VARCHAR (255) NULL,
    [SRCountry]             CHAR (3)      NULL,
    [SREmail]               VARCHAR (255) NULL,
    [SREmail2]              VARCHAR (50)  NULL,
    [SRFax]                 VARCHAR (20)  NULL,
    [SRState]               VARCHAR (255) NULL,
    [SRZipCode]             VARCHAR (50)  NULL,
    [DTAddress1]            VARCHAR (255) NULL,
    [DTAddress2]            VARCHAR (255) NULL,
    [DTAddrName]            VARCHAR (255) NULL,
    [DTCity]                VARCHAR (255) NULL,
    [DTCountry]             CHAR (3)      NULL,
    [DTEmail]               VARCHAR (255) NULL,
    [DTEmail2]              VARCHAR (50)  NULL,
    [DTFax]                 VARCHAR (20)  NULL,
    [DTState]               VARCHAR (255) NULL,
    [DTZipCode]             VARCHAR (50)  NULL,
    [RTAddress1]            VARCHAR (255) NULL,
    [RTAddress2]            VARCHAR (255) NULL,
    [RTAddrName]            VARCHAR (255) NULL,
    [RTCity]                VARCHAR (255) NULL,
    [RTCountry]             CHAR (3)      NULL,
    [RTEmail]               VARCHAR (255) NULL,
    [RTEmail2]              VARCHAR (50)  NULL,
    [RTFax]                 VARCHAR (20)  NULL,
    [RTState]               VARCHAR (255) NULL,
    [RTZipCode]             VARCHAR (50)  NULL,
    [BAAddress1]            VARCHAR (255) NULL,
    [BAAddress2]            VARCHAR (255) NULL,
    [BAAddrName]            VARCHAR (255) NULL,
    [BACity]                VARCHAR (255) NULL,
    [BACountry]             CHAR (3)      NULL,
    [BAEmail]               VARCHAR (255) NULL,
    [BAEmail2]              VARCHAR (50)  NULL,
    [BAFax]                 VARCHAR (20)  NULL,
    [BAState]               VARCHAR (255) NULL,
    [BAZipCode]             VARCHAR (50)  NULL,
    [CreatedUsedName]       VARCHAR (50)  NULL,
    [AllowOrderDelete]      BIT           NULL,
    [CSRKey]                INT           NULL,
    [CSRName]               VARCHAR (100) NULL,
    [SalesPersonKey]        INT           NULL,
    [SalesPersonName]       VARCHAR (100) NULL,
    [CSRManagerKey]         INT           NULL,
    [CSRManagerName]        VARCHAR (100) NULL,
    [MarketLocationKey]     INT           NULL,
    [MarketLocation]        VARCHAR (100) NULL,
    [OrderSource]           VARCHAR (20)  NULL,
    [Consignee]             VARCHAR (100) NULL
);

