CREATE TABLE [dbo].[Routes_538980] (
    [RouteKey]                     INT             IDENTITY (1, 1) NOT NULL,
    [OrderDetailKey]               INT             NOT NULL,
    [OrderKey]                     INT             NULL,
    [LegKey]                       SMALLINT        NOT NULL,
    [LegNo]                        SMALLINT        NULL,
    [SourceAddrKey]                INT             NULL,
    [PickupDateFrom]               SMALLDATETIME   NULL,
    [PickupDateTo]                 SMALLDATETIME   NULL,
    [CutOffDate]                   DATETIME        NULL,
    [DeliveryDateFrom]             SMALLDATETIME   NULL,
    [DeliveryDateTo]               SMALLDATETIME   NULL,
    [AppointmentNo]                VARCHAR (500)   NULL,
    [ConfirmationNo]               VARCHAR (50)    NULL,
    [LastFreeDay]                  DATETIME        NULL,
    [SwitchTo]                     VARCHAR (50)    NULL,
    [PortWaitingTimeFrom]          DATETIME        NULL,
    [PortWaitingTimeTo]            DATETIME        NULL,
    [CustomerWaitingTimeFrom]      DATETIME        NULL,
    [CustomerWaitingTimeTo]        DATETIME        NULL,
    [ChassisNo]                    VARCHAR (50)    NULL,
    [ChassisType]                  VARCHAR (30)    NULL,
    [TruckNo]                      VARCHAR (50)    NULL,
    [FromLocation]                 VARCHAR (255)   NULL,
    [ToLocation]                   VARCHAR (255)   NULL,
    [DestinationAddrKey]           INT             NULL,
    [EstimatedDistanceInMiles]     DECIMAL (18, 2) NULL,
    [EstimatedTravelTime]          DECIMAL (5, 2)  NULL,
    [Status]                       SMALLINT        NULL,
    [DriverKey]                    INT             NULL,
    [ScheduledPickupDate]          DATETIME        NULL,
    [ScheduledArrival]             DATETIME        NULL,
    [ScheduledDeparture]           DATETIME        NULL,
    [ActualDeparture]              DATETIME        NULL,
    [ActualArrival]                DATETIME        NULL,
    [OdometerAtSource]             SMALLINT        NULL,
    [OdometerAtDestination]        SMALLINT        NULL,
    [DriverCommentKey]             INT             NULL,
    [SchedulerCommentKey]          INT             NULL,
    [ChassisKey]                   INT             NULL,
    [CompanyKey]                   SMALLINT        NULL,
    [CreateUserKey]                INT             NULL,
    [UpdateUserKey]                INT             NULL,
    [CreateDate]                   DATETIME        NULL,
    [LastUpdateDate]               DATETIME        NULL,
    [LocationKey]                  INT             NULL,
    [IsEmpty]                      BIT             NULL,
    [IsAbandoned]                  BIT             NULL,
    [IsDryRun]                     BIT             NULL,
    [IsBobtail]                    BIT             NULL,
    [IsDocumentVerified]           BIT             NULL,
    [IsRateVerified]               BIT             NULL,
    [DocumentVerifiedDate]         DATETIME        NULL,
    [RateVerifiedDate]             DATETIME        NULL,
    [DocumentVerifiedUserKey]      INT             NULL,
    [RateVerifiedUserKey]          INT             NULL,
    [DelConfirmationNo]            VARCHAR (50)    NULL,
    [isStreetTurn]                 BIT             NULL,
    [StreetTurnSetUser]            INT             NULL,
    [StreetTurnSetDate]            DATETIME        NULL,
    [IsChargesApproved]            BIT             NULL,
    [ChargesApprovedDate]          DATETIME        NULL,
    [ChargesApprovedBy]            INT             NULL,
    [DryRunType]                   INT             NULL,
    [YardCheckIn]                  DATETIME        NULL,
    [YardCheckOut]                 DATETIME        NULL,
    [ChassisCategoryKey]           INT             NULL,
    [ActualDepartureUpdateMethod]  VARCHAR (20)    NULL,
    [ActualArrivalUpdateMethod]    VARCHAR (20)    NULL,
    [CarrierRate]                  DECIMAL (18)    NULL,
    [StreeTurnPrevStatusKey]       INT             NULL,
    [EmptySetUser]                 INT             NULL,
    [EmptySetDate]                 DATETIME        NULL,
    [BobtailSetUser]               INT             NULL,
    [BobtailSetDate]               DATETIME        NULL,
    [DryRunSetUser]                INT             NULL,
    [DryRunSetDate]                DATETIME        NULL,
    [SFGYardDiffLogKeyPickup]      INT             NULL,
    [SFGYardChangePickup]          VARCHAR (20)    NULL,
    [SFGYardChangePickupMessage]   VARCHAR (500)   NULL,
    [SFGYardDiffLogKeyDelivery]    INT             NULL,
    [SFGYardChangeDelivery]        VARCHAR (20)    NULL,
    [SFGYardChangeDeliveryMessage] VARCHAR (500)   NULL,
    [YardIDPickupBeforeUpdate]     INT             NULL,
    [YardIDDeliveryBeforeUpdate]   INT             NULL,
    [PrevStatusKey]                INT             NULL,
    [ChassisSource]                VARCHAR (100)   NULL,
    [ChassisChangedDate]           DATETIME        NULL,
    [EmptySource]                  VARCHAR (100)   NULL,
    [DryRunSource]                 VARCHAR (100)   NULL,
    [BobTailSource]                VARCHAR (100)   NULL,
    [StreetTurnSource]             VARCHAR (100)   NULL,
    [ChassisChangedUser]           INT             NULL,
    [ActualDepartureUpdateDate]    DATETIME        NULL,
    [ActualDepartureUpdateUser]    INT             NULL,
    [ActualArrivalUpdateDate]      DATETIME        NULL,
    [ActualArrivalUpdateUser]      INT             NULL,
    [ChargeNotes]                  NVARCHAR (MAX)  NULL,
    [CompletionNotes]              NVARCHAR (MAX)  NULL,
    [DriverInstructions]           VARCHAR (1000)  NULL,
    [FromLocationWaitTimeFrom]     DATETIME        NULL,
    [FromLocationWaitTimeTo]       DATETIME        NULL,
    [ToLocationWaitTimeFrom]       DATETIME        NULL,
    [ToLocationWaitTimeTo]         DATETIME        NULL,
    [CarrierAssignedBy]            INT             NULL,
    [LinkedContainer]              VARCHAR (20)    NULL,
    [LinkedBy]                     INT             NULL,
    [LinkedDate]                   DATE            NULL,
    [ContainerNoSource]            VARCHAR (100)   NULL,
    [NoEmptyAvailableMarked]       BIT             NULL,
    [NoEmptyAvailableMarkedBY]     INT             NULL,
    [NoEmptyAvailableMarkedDate]   DATETIME        NULL,
    [LegType]                      VARCHAR (50)    NULL,
    [IsChassisSplit]               BIT             NULL,
    [LinkedContainerSource]        NVARCHAR (20)   NULL,
    [NoEmptyMarkedSource]          NVARCHAR (20)   NULL
);

