CREATE TABLE [dbo].[SELL_NAC_Accessorial_FileUploadData_AllData11042025] (
    [FileProcessKey]    INT             NOT NULL,
    [RecordSL]          INT             NOT NULL,
    [CustID]            VARCHAR (50)    NULL,
    [CustName]          VARCHAR (200)   NULL,
    [RateType]          VARCHAR (10)    NULL,
    [Segment]           VARCHAR (10)    NULL,
    [MarketLocation]    VARCHAR (50)    NULL,
    [Terminal]          VARCHAR (50)    NULL,
    [LineItem]          VARCHAR (100)   NULL,
    [City]              VARCHAR (100)   NULL,
    [State]             VARCHAR (20)    NULL,
    [Zip]               VARCHAR (20)    NULL,
    [LocationName]      VARCHAR (100)   NULL,
    [IsLocationExists]  VARCHAR (10)    NULL,
    [Rate]              NUMERIC (18, 2) NULL,
    [BvsNB]             VARCHAR (5)     NULL,
    [FreeTime]          INT             NULL,
    [MinCnt]            INT             NULL,
    [MaxCnt]            INT             NULL,
    [ContainerSize]     VARCHAR (50)    NULL,
    [EffectiveDate]     VARCHAR (50)    NULL,
    [EffectiveDateFrom] VARCHAR (50)    NULL,
    [Remarks]           VARCHAR (MAX)   NULL,
    [ExpiryDate]        NVARCHAR (50)   NULL,
    [OrderType]         NVARCHAR (100)  NULL,
    [Consignee]         NVARCHAR (100)  NULL,
    [TruckType]         NVARCHAR (100)  NULL,
    [IsArchived]        BIT             NULL
);

