CREATE TABLE [dbo].[Sell_AccessorialRates] (
    [SellAccRateKey] INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketKey]      INT             NULL,
    [ZoneKey]        INT             NULL,
    [YardPort]       VARCHAR (20)    NULL,
    [LineItem]       VARCHAR (200)   NULL,
    [Cost]           NUMERIC (18, 2) NULL,
    [SMB_Margin]     NUMERIC (18, 2) NULL,
    [SMB_Rate]       NUMERIC (18, 2) NULL,
    [SMB_BvsNB]      VARCHAR (5)     NULL,
    [SMB_FreeTime]   INT             NULL,
    [SMB_Min]        INT             NULL,
    [SMB_Max]        INT             NULL,
    [SMB_NetRevenue] NUMERIC (18, 2) NULL,
    [SMB_UserKey]    INT             NULL,
    [SMB_Date]       DATETIME        NULL,
    [ENT_Margin]     NUMERIC (18, 2) NULL,
    [ENT_Rate]       NUMERIC (18, 2) NULL,
    [ENT_BvsNB]      VARCHAR (5)     NULL,
    [ENT_FreeTime]   INT             NULL,
    [ENT_Min]        INT             NULL,
    [ENT_Max]        INT             NULL,
    [ENT_NetRevenue] NUMERIC (18, 2) NULL,
    [ENT_Date]       DATETIME        NULL,
    [ENT_UserKey]    INT             NULL,
    [NAC_Margin]     NUMERIC (18, 2) NULL,
    [NAC_Rate]       NUMERIC (18, 2) NULL,
    [NAC_BvsNB]      VARCHAR (5)     NULL,
    [NAC_FreeTime]   INT             NULL,
    [NAC_Min]        INT             NULL,
    [NAC_Max]        INT             NULL,
    [NAC_NetRevenue] NUMERIC (18, 2) NULL,
    [NAC_UserKey]    INT             NULL,
    [NAC_Date]       DATETIME        NULL,
    CONSTRAINT [PK__Sell_Acc__ACB90460743ABEB8] PRIMARY KEY CLUSTERED ([SellAccRateKey] ASC) WITH (FILLFACTOR = 90)
);

