CREATE TABLE [dbo].[TempCutomer_202410] (
    [CustKey]            INT             IDENTITY (1, 1) NOT NULL,
    [CustID]             VARCHAR (100)   NOT NULL,
    [CustName]           VARCHAR (100)   NOT NULL,
    [AddrKey]            INT             NOT NULL,
    [CreateDate]         DATETIME        NOT NULL,
    [CustomerGroup]      SMALLINT        NULL,
    [StatusKey]          SMALLINT        NOT NULL,
    [StatusDate]         DATETIME        NOT NULL,
    [CreditCheck]        BIT             NULL,
    [CreditLimit]        DECIMAL (18, 2) NULL,
    [CreditStatus]       SMALLINT        NULL,
    [Ach_Required]       BIT             NULL,
    [PaymentTermsKey]    SMALLINT        NOT NULL,
    [CompanyKey]         SMALLINT        NOT NULL,
    [BillToAddrKey]      INT             NULL,
    [IsFactored]         BIT             NULL,
    [Notes]              VARCHAR (1000)  NULL,
    [IsActive]           BIT             NULL,
    [IsDelete]           BIT             NULL,
    [CSRKey]             INT             NULL,
    [CSRManagerKey]      INT             NULL,
    [SalesPersonKey]     INT             NULL,
    [MarketLocationKey]  INT             NULL,
    [CustomerSegmentKey] INT             NULL,
    [CustomerNotes]      NVARCHAR (MAX)  NULL,
    [CustomerCompanyKey] INT             NULL,
    [RateTypeKey]        INT             NULL,
    [IncludeFSF]         BIT             NULL,
    [RatePercent]        DECIMAL (18, 2) NULL,
    [IsMaster]           BIT             NULL,
    [MasterCustKey]      INT             NULL
);

