CREATE TABLE [dbo].[TempAccessorial_Delete] (
    [Rownum]            BIGINT          NULL,
    [OutputDataKey]     BIGINT          NOT NULL,
    [RecordSL]          INT             NULL,
    [MarketKey]         INT             NULL,
    [Terminal]          VARCHAR (50)    NULL,
    [City]              VARCHAR (100)   NULL,
    [State]             VARCHAR (20)    NULL,
    [Zip]               VARCHAR (20)    NULL,
    [LocationName]      VARCHAR (100)   NULL,
    [ContainerSize]     VARCHAR (50)    NULL,
    [ContainerSizeKey]  INT             NULL,
    [CustKey]           INT             NULL,
    [CustName]          VARCHAR (200)   NULL,
    [EffectiveDate]     VARCHAR (50)    NULL,
    [EffectiveDateFrom] VARCHAR (50)    NULL,
    [IsLocationExists]  VARCHAR (10)    NULL,
    [ItemKey]           INT             NOT NULL,
    [LineItem]          VARCHAR (100)   NULL,
    [MarketLocation]    VARCHAR (50)    NULL,
    [Segment]           VARCHAR (10)    NULL,
    [SegmentKey]        INT             NULL,
    [TerminalKey]       INT             NULL,
    [Rate]              NUMERIC (18, 2) NULL,
    [BvsNB]             VARCHAR (5)     NULL,
    [FreeTime]          INT             NULL,
    [MinCnt]            INT             NULL,
    [MaxCnt]            INT             NULL,
    [CostGroup]         NVARCHAR (300)  NULL,
    [FileName]          VARCHAR (100)   NULL,
    [DateUploaded]      DATETIME        NULL,
    [UploadedBy]        VARCHAR (50)    NOT NULL
);

