CREATE TABLE [dbo].[ToInvoice] (
    [InvoiceKey]             INT             NOT NULL,
    [OrderKey]               INT             NOT NULL,
    [OrderDetailKey]         INT             NOT NULL,
    [OrderNo]                VARCHAR (50)    NULL,
    [ContainerNo]            VARCHAR (500)   NULL,
    [ActualArrival]          DATETIME        NULL,
    [CustId]                 VARCHAR (100)   NULL,
    [CustName]               VARCHAR (200)   NULL,
    [IsInvoiceApproved]      BIT             NULL,
    [StatusKey]              SMALLINT        NULL,
    [InvoiceAmount]          NUMERIC (18, 2) NULL,
    [City]                   VARCHAR (50)    NULL,
    [Status]                 VARCHAR (50)    NULL,
    [DestinationAddrKey]     INT             NULL,
    [InvoiceNo]              VARCHAR (50)    NULL,
    [InvoiceDate]            DATETIME        NULL,
    [DocumentCount]          INT             NULL,
    [IsPrinted]              BIT             NULL,
    [PrintedUserKey]         INT             NULL,
    [PaymentRecdUserKey]     INT             NULL,
    [PaymentRecdDate]        DATETIME        NULL,
    [PrintedDate]            DATETIME        NULL,
    [IsRevised]              BIT             NULL,
    [RevisionDate]           DATETIME        NULL,
    [BrokerRefNo]            VARCHAR (50)    NULL,
    [IsFactored]             BIT             NULL,
    [VesselETA]              VARCHAR (50)    NULL,
    [BalanceAmount]          NUMERIC (18, 2) NULL,
    [CustKey]                INT             NULL,
    [OrderDate]              DATETIME        NULL,
    [BillOfLading]           VARCHAR (50)    NULL,
    [OrderType]              VARCHAR (50)    NULL,
    [BookingNo]              VARCHAR (50)    NULL,
    [TerminationDate]        DATETIME        NULL,
    [ContainerList]          VARCHAR (MAX)   NULL,
    [AddrName]               VARCHAR (100)   NULL,
    [MarketLocationKey]      INT             NULL,
    [MarketLocation]         VARCHAR (100)   NULL,
    [IsPaymentReceived]      BIT             NULL,
    [RevisionUserKey]        INT             NULL,
    [InvoiceApprovedUserKey] INT             NULL,
    [CustomerNote]           VARCHAR (MAX)   NULL,
    [InternalNote]           VARCHAR (MAX)   NULL,
    [CustApproved]           BIT             NULL,
    [InvoicerKey]            VARCHAR (MAX)   NULL,
    [InvoicerName]           VARCHAR (100)   NULL,
    [ReasonCodeKey]          INT             NULL,
    [ReasonCodeName]         VARCHAR (100)   NULL,
    [CustCompanyKey]         INT             NULL,
    [AgingDays]              INT             NULL,
    [AprovedReasonCodeKey]   INT             NULL,
    [ApprovedReasonCode]     VARCHAR (100)   NULL,
    [CustCompanyName]        VARCHAR (500)   NULL,
    [RouteKey]               INT             NULL,
    [LegID]                  VARCHAR (100)   NULL,
    [IsDataSelected]         BIT             NULL,
    [IsSelectedStatusKey]    BIT             NULL,
    [CSR]                    VARCHAR (100)   NULL,
    [WarehouseStatus]        VARCHAR (100)   NULL,
    [AllowInvoicing]         BIT             NULL,
    [IsCSChargesApproved]    BIT             NULL,
    [CSChargesApproveDate]   DATETIME        NULL,
    [ExpCount]               INT             CONSTRAINT [DF__ToInvoice__ExpCo__13E89FA1] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ToInvoice] PRIMARY KEY CLUSTERED ([InvoiceKey] ASC, [OrderKey] ASC, [OrderDetailKey] ASC)
);

